[MON-1]Added Page to show list of recipients
diging/monitor pull request #12
Opened 2020-02-21 20:41 UTC by coder-aakash994

Created new PR as previous one was tracking changes from MON-7 and MON-3

2020-02-21 20:49 UTC, jdamerow requested changes

2020-02-21 20:49 UTC, jdamerow commented on monitor/src/main/java/edu/asu/diging/monitor/core/service/INotificationManager.java
> +	Map<String,String> showRecipients();
how about calling this `getRecipients` or `getAllRecipients` since this method doesn't show anything?

2020-02-21 20:49 UTC, jdamerow commented on monitor/src/main/java/edu/asu/diging/monitor/core/service/impl/NotificationManager.java
> +		return recipientInfo;
why doesn't this method return a list of recipients?

2020-02-21 20:49 UTC, jdamerow commented on monitor/src/main/java/edu/asu/diging/monitor/core/service/impl/NotificationManager.java
> +		return recipientInfo;
if we add more properties to the recipient class later, we don't want to change this method.

2020-02-21 20:49 UTC, jdamerow commented on monitor/src/main/java/edu/asu/diging/monitor/web/admin/AddRecipientController.java
> +	@RequestMapping(value="/admin/recipients/show", method=RequestMethod.GET)
this should be in its own controller (it has nothing to do with adding recipients); also, let's just make it `/admin/recipients` or `/admin/recipient/list`

2020-02-21 20:49 UTC, jdamerow commented on monitor/src/main/java/edu/asu/diging/monitor/web/admin/AddRecipientController.java
> +		List<RecipientForm> recipientList = new ArrayList<>();
why are you using the form class here? it's for the list of recipients, not for a form, right?

2020-02-21 20:49 UTC, jdamerow commented on monitor/src/main/java/edu/asu/diging/monitor/web/admin/AddRecipientController.java
> +		model.addAttribute("rcpts", recipientList);
let's give the attributes understandable names (e.g. `recipients`)

2020-02-21 20:49 UTC, jdamerow commented on monitor/src/main/java/edu/asu/diging/monitor/web/admin/AddRecipientController.java
> +		return "admin/recipients/showAddPage";
how about just `admin/recipients/add`?

2020-02-21 22:18 UTC, coder-aakash994 commented
I have made the requested changes in the latest commit

2020-02-24 17:08 UTC, jdamerow commented
Jenkins, test this please.

2020-02-24 17:36 UTC, jdamerow requested changes

2020-02-24 17:36 UTC, jdamerow commented on monitor/src/main/java/edu/asu/diging/monitor/web/admin/AddRecipientController.java
> +		return "admin/recipients/add";
for the below method: after a new user has been added, the list page should be shone.

2020-02-24 17:36 UTC, jdamerow commented on monitor/src/main/java/edu/asu/diging/monitor/core/service/impl/NotificationManager.java
> +	}
let's write a test case for this.

2020-02-25 21:57 UTC, jdamerow requested changes

2020-02-25 21:57 UTC, jdamerow commented on monitor/src/main/java/edu/asu/diging/monitor/web/admin/AddRecipientController.java
> +			redirectURL = "redirect:/admin/recipients/add";
return here

2020-02-25 21:57 UTC, jdamerow commented on monitor/src/main/java/edu/asu/diging/monitor/web/admin/AddRecipientController.java
> +				redirectURL = "redirect:/admin/recipient/list";
return here

2020-02-25 21:57 UTC, jdamerow commented on monitor/src/main/java/edu/asu/diging/monitor/web/admin/AddRecipientController.java
> +				redirectURL = "redirect:/admin/recipients/add";
return here

2020-02-26 14:25 UTC, jdamerow requested changes

2020-02-26 14:25 UTC, jdamerow commented on monitor/src/main/java/edu/asu/diging/monitor/web/admin/AddRecipientController.java
>  		} else {
loose the else block, it's not needed if you return in the if block

2020-02-27 19:56 UTC, merged