Story/MON-12
diging/monitor pull request #19
Opened 2020-04-07 18:14 UTC by coder-aakash994

2020-04-07 19:51 UTC, jdamerow requested changes

2020-04-07 19:51 UTC, jdamerow commented on monitor/src/main/java/edu/asu/diging/monitor/core/db/impl/AppDbConnection.java
> +
please fix formatting

2020-04-07 19:51 UTC, jdamerow commented on monitor/src/main/java/edu/asu/diging/monitor/core/service/impl/NotificationManager.java
> +        }
indentation

2020-04-07 19:51 UTC, jdamerow commented on monitor/src/main/java/edu/asu/diging/monitor/core/service/impl/NotificationManager.java
> +    public void sendNotificationEmails(IApp app, AppStatus previousStatus) {
indentation, also, what does the comment mean?

2020-04-07 19:51 UTC, jdamerow commented on monitor/src/main/java/edu/asu/diging/monitor/core/service/impl/NotificationManager.java
> +                recipients.add(recipient);
- please follow our style guide
- also, why do you add all recipients  into a new list?

2020-04-07 19:51 UTC, jdamerow commented on monitor/src/main/java/edu/asu/diging/monitor/web/admin/AddRecipientController.java
> +        recipientForm.setApps(appManager.getApps().stream().map(x -> {
`x` is a pretty bad variable name. even in a lambda function, it should be somewhat related to the object e.g. `a` for app

2020-04-07 19:51 UTC, jdamerow commented on monitor/src/main/java/edu/asu/diging/monitor/core/service/impl/NotificationManager.java
> +		recipient.setApps(apps);
merge with line 54

2020-04-09 17:39 UTC, jdamerow commented
Jenkins, test this please.

2020-04-09 17:45 UTC, jdamerow commented
The select all checkbox just looks like an app without a name, that needs to be changed (it should not be part of the list and have a label). Also, the apps should show who is getting notified. And the recipient list should show what apps are being watched.

2020-04-10 18:45 UTC, jdamerow commented
- It should say "all" for recipients if an app notification is send to everybody.
- recipients should only be shown after login (not sure, if said otherwise before, if so, I'm sorry for the confusion)
- when adding or editing an app, we need to be able to select who gets notified. right now if I would add an app, I couldn't select any existing users to get notifications, only all.
- the select/deselect all checkbox needs to be visually different from the other checkboxes

2020-04-24 20:45 UTC, jdamerow commented
Jenkins, test this please.

2020-04-24 20:47 UTC, jdamerow requested changes

2020-04-24 20:47 UTC, jdamerow commented on monitor/src/main/java/edu/asu/diging/monitor/core/db/impl/AppDbConnection.java
> +            em.persist(app);
please follow our style guide

2020-04-24 20:47 UTC, jdamerow commented on monitor/src/main/java/edu/asu/diging/monitor/core/db/impl/AppDbConnection.java
> +            em.persist(app);
same here

2020-04-24 21:19 UTC, jdamerow commented
not sure if it has been introduced earlier or with this PR, but editing  of an app doesn't seem to work (editing the url)

2020-04-25 21:14 UTC, coder-aakash994 commented
are you talking about the healthUrl because I am able to update it locally while editing.

2020-04-30 17:58 UTC, jdamerow commented
There is some kind of endless recursion happening now. When polling, it gets all recipients for an app, then all apps for a recipient, with all apps, with all recipients...

2020-04-30 17:58 UTC, closed without merging

2020-04-30 17:58 UTC, jdamerow requested changes

2020-04-30 17:58 UTC, jdamerow commented on monitor/src/main/java/edu/asu/diging/monitor/core/db/impl/AppDbConnection.java
> +		}
indentation

2020-04-30 17:58 UTC, jdamerow commented on monitor/src/main/java/edu/asu/diging/monitor/core/db/impl/AppDbConnection.java
> +		}
indentation

2020-04-30 17:58 UTC, jdamerow commented on monitor/src/main/java/edu/asu/diging/monitor/web/admin/forms/AppForm.java
> +    }
formatting