Story/MON-12
diging/monitor pull request #20
Opened 2020-05-05 17:24 UTC by coder-aakash994

Opening a new PR after merging changes with develop.

2020-05-05 18:57 UTC, jdamerow requested changes
please fix indentation (should be 4 or 6 (if you follow what's already used) spaces but not 8) and follow our style guide before I keep reviewing.

2020-05-05 19:22 UTC, coder-aakash994 commented
hope this is okay.

2020-05-05 20:29 UTC, jdamerow requested changes

2020-05-05 20:29 UTC, jdamerow commented on monitor/src/main/java/edu/asu/diging/monitor/core/db/impl/AppDbConnection.java
> +        else {
please follow our styleguide

2020-05-05 20:29 UTC, jdamerow commented on monitor/src/main/java/edu/asu/diging/monitor/core/model/impl/App.java
> +	}
formatting

2020-05-05 20:29 UTC, jdamerow commented on monitor/src/main/java/edu/asu/diging/monitor/core/service/impl/AppHelper.java
> +            app.setRecipients(getRecipientsById(appForm.getRecipientIds()));
code style

2020-05-05 20:29 UTC, jdamerow commented on monitor/src/main/java/edu/asu/diging/monitor/web/admin/ModifyAppController.java
> +            appManager.deleteExistingRecipients(app);
code style

2020-05-05 20:29 UTC, jdamerow commented
Jenkins, test this please.

2020-05-05 20:48 UTC, jdamerow commented
once the formatting issues are fixed, should be good to go.

2020-05-06 19:27 UTC, jdamerow approved these changes

2020-05-06 19:28 UTC, merged